# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x07network\"\'\n\x10RecognizeRequest\x12\x13\n\x0b\x62itmap_data\x18\x01 \x01(\x0c\"8\n\x11RecognizeResponse\x12\x12\n\nhandedness\x18\x01 \x01(\t\x12\x0f\n\x07gesture\x18\x02 \x01(\t2^\n\x16RemoteRecognizeService\x12\x44\n\trecognize\x12\x19.network.RecognizeRequest\x1a\x1a.network.RecognizeResponse\"\x00\x42:\n\x19\x63om.narc.arclient.networkB\x1bRemoteRecognizeServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.narc.arclient.networkB\033RemoteRecognizeServiceProtoP\001'
  _globals['_RECOGNIZEREQUEST']._serialized_start=25
  _globals['_RECOGNIZEREQUEST']._serialized_end=64
  _globals['_RECOGNIZERESPONSE']._serialized_start=66
  _globals['_RECOGNIZERESPONSE']._serialized_end=122
  _globals['_REMOTERECOGNIZESERVICE']._serialized_start=124
  _globals['_REMOTERECOGNIZESERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
