# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import server_pb2 as server__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RemoteRecognizeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.recognize = channel.unary_unary(
                '/network.RemoteRecognizeService/recognize',
                request_serializer=server__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=server__pb2.RecognizeResponse.FromString,
                _registered_method=True)
        self.logReport = channel.unary_unary(
                '/network.RemoteRecognizeService/logReport',
                request_serializer=server__pb2.LogReportRequest.SerializeToString,
                response_deserializer=server__pb2.EmptyResponse.FromString,
                _registered_method=True)
        self.systemState = channel.unary_unary(
                '/network.RemoteRecognizeService/systemState',
                request_serializer=server__pb2.SystemStateRequest.SerializeToString,
                response_deserializer=server__pb2.EmptyResponse.FromString,
                _registered_method=True)


class RemoteRecognizeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def recognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def logReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def systemState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteRecognizeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.recognize,
                    request_deserializer=server__pb2.RecognizeRequest.FromString,
                    response_serializer=server__pb2.RecognizeResponse.SerializeToString,
            ),
            'logReport': grpc.unary_unary_rpc_method_handler(
                    servicer.logReport,
                    request_deserializer=server__pb2.LogReportRequest.FromString,
                    response_serializer=server__pb2.EmptyResponse.SerializeToString,
            ),
            'systemState': grpc.unary_unary_rpc_method_handler(
                    servicer.systemState,
                    request_deserializer=server__pb2.SystemStateRequest.FromString,
                    response_serializer=server__pb2.EmptyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'network.RemoteRecognizeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('network.RemoteRecognizeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteRecognizeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/network.RemoteRecognizeService/recognize',
            server__pb2.RecognizeRequest.SerializeToString,
            server__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def logReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/network.RemoteRecognizeService/logReport',
            server__pb2.LogReportRequest.SerializeToString,
            server__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def systemState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/network.RemoteRecognizeService/systemState',
            server__pb2.SystemStateRequest.SerializeToString,
            server__pb2.EmptyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
